### ISSUE TITLE
Autocomplete crashes with a document containing PlantUML (extension) diagrams

### ISSUE THREAD

**Issue by fuhrmanator** [quarto-dev/quarto-vscode#100]
Autocomplete for bibliography or cross-ref (i.e., as soon as I type `@` in one of my `.qmd` files that contains fenced PlantUML blocks) results in an error pop-up:

![image](https://user-images.githubusercontent.com/7606540/196518058-3278396a-3659-4089-a620-b825c18a54ad.png)

```
Error running filter C:/Users/Me/AppData/Local/Programs/Quarto/share/filters/crossref/crossref.lua:
...ocal/Programs/Quarto/share/filters/crossref/crossref.lua:827: attempt to get length of a nil value (field 'content')
stack traceback:
	...ocal/Programs/Quarto/share/filters/crossref/crossref.lua:2905: in function <...ocal/Programs/Quarto/share/filters/crossref/crossref.lua:2820>
[Error - 2:49:10 p.m.] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Command failed: C:\Users\Me\AppData\Local\Programs\Quarto\bin\tools\pandoc --defaults defaults.yml
Error running filter C:/Users/Me/AppData/Local/Programs/Quarto/share/filters/crossref/crossref.lua:
...ocal/Programs/Quarto/share/filters/crossref/crossref.lua:827: attempt to get length of a nil value (field 'content')
stack traceback:
	...ocal/Programs/Quarto/share/filters/crossref/crossref.lua:2905: in function <...ocal/Programs/Quarto/share/filters/crossref/crossref.lua:2820>

  Code: -32603 
```

Here's a sample file that will cause the crash (I don't think you need to install the filter, but it's the standard LUA filter with pandoc):

````markdown
---
filters: 
  - filters/diagram-generator.lua

---

# Test

Here's a diagram:

```{.plantuml  #fig-sd caption="Sequence diagram"}
A -> B : Hello
```

````

I think the bug is related to the `#fig-sd` element, since if I remove that, the cross-ref autocompletion doesn't crash.

Edit: I'm on Windows 10 with latest Quarto 1.1.251 and quarto-vscode v1.48.0

**Comment by jjallaire** [comment]
Thanks for reporting this! The issue is actually in quarto-cli so the fix is there: https://github.com/quarto-dev/quarto-cli/commit/38b7b765c5594fa19a73f854eefe2c98fdb3cdc8

Should be a new v1.2 pre-release with this fix available later this morning.

**Comment by fuhrmanator** [comment]
I installed the pre-release this morning and the problem is gone. Thanks for such a quick turn-around!

**Comment by jjallaire** [comment]
Great! Thanks for letting us know.
