### ISSUE TITLE
render button feeds absolute windows path to wsl terminal resulting in error (file not found)

### ISSUE THREAD

**Issue by kompre** [quarto-dev/quarto-vscode#104]
Hello,

I just learned about quarto and would like to give it a try. 

I use vs-code on a windows machine, but I prefer to use wsl as my default terminal (ubuntu). Quarto is installed also in the wsl.

When I click on the render button, a new terminal is open, but the command fails because the file path is windows-like, and obviously can't be found:

```
quarto preview c:/Users/path-to-folder/quarto.qmd --no-browser --no-watch-inputs

ERROR: c:/Users/path-to-folder/quarto.qmd not found

```

I wasn't able to find an option for using relative path, that would fix this error (since that files reside in the current working directory).

The easy fix is to change the default terminal to powershell, but it is a little bit of an hassle.

**Comment by jjallaire** [comment]
I made a change to use a relative path when running under WSL (I don't have WSL but based on my research this should detect it correctly): https://github.com/quarto-dev/quarto-vscode/commit/e57bc61aa90e4cc7054db5234b8c19e1d56e1f78. This change is available now in v1.52.0 of the extension.

Note that before we launch the terminal we set the cwd to the folder containing the input file. Hopefully that path is correctly translated and applied (could run into the same issue there?).

**Comment by jjallaire** [comment]
Okay, I've reverted that fix as it clearly breaks WSL in other scenarios (fix is available in v1.53.0)

**Comment by jjallaire** [comment]
@kompre I don't think we can resolve this right now (without digging much deeper into the relationship between VS Code Terminals and WSL). You can see that for at least one other users they are getting "unix-style" paths in WSL sessions. Further, the fact that WSL seems to ignore the working directory setting of the created terminal throws another wrench in things. For now I'd just use PowerShell for Quarto projects and hopefully we can spend more time on WSL soon.

**Comment by kompre** [comment]
Yeah, i was thinking of using powershell for quarto either way because I got also shenanigans trying to render to pdf with the texlive installation...

I think I just need to delve a little bit in the workspace settings of vscode so that it will use powershell as default instead of WSL.

WSL is nice to have but sometimes could be tricky
