### ISSUE TITLE
Quarto is unable to find the correct R version. 

### ISSUE THREAD

**Issue by Fred-Wu** [quarto-dev/quarto-vscode#107]
I have two versions of R installed on my Windows machine. One is R 4.1.3 and the other one is R 4.2.1. 

I am using VSCode-R, and native R terminal in VSCode, in which the R terminal path is specified to R 4.2.1, the version I am mainly using.  Two versions also have different library paths. 

When I built `qmd` in RStudio, it was a success. 

However, with `quarto-vscode` for the same `qmd` file, it finds R 4.1.3 instead of R 4.2.1 by default, and then runs into error. 

```
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/xxxxxx/AppData/Local/R/win-library/4.2/rlang/libs/x64/rlang.dll':
  LoadLibrary failure:  The specified procedure could not be found.
Calls: .main ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load -> inDL
Execution halted

R installation:
  Version: 4.1.3
  Path: C:/PROGRA~1/R/R-41~1.3
  LibPaths:
    - C:/Users/xxxxxx/AppData/Local/R/win-library/4.2
    - C:/Program Files/R/R-4.1.3/library
  rmarkdown: (None)

The rmarkdown package is not available in this R installation.
Install with install.packages("rmarkdown")
```

**Comment by jjallaire** [comment]
We determine which version of R to use within VS Code by looking at the `r.rpath.windows` config setting made available by the VS Code extension. Is there another setting you are aware of we should be consulting here?

**Comment by Fred-Wu** [comment]
Both of my `r.rterm.windows` and `r.rpath.windows` were set to R 4.2.1 as

```
"r.rterm.windows": "C:\\Program Files\\R\\R-4.2.1\\bin\\R.exe",
"r.rpath.windows": "C:\\Program Files\\R\\R-4.2.1\\bin\\R.exe",
```

**Comment by mcanouil** [comment]
By default `vscode-r` is looking for R in Windows registry (suggesting R was installed with the "save version number in registry" option checked).
It might be that `vscode-r` first get that version then overwrite the value with `r.rterm.windows`.

By the way, according to the Wiki (<https://github.com/REditorSupport/vscode-R/wiki/Installation:-Windows#vscode-r>) `r.rterm.windows` seems to be the setting to look for (not `r.path.windows`) at least for interactive terminal.

- `r.rpath.windows`
  > Path to an R executable to launch R background processes (Windows). Must be \"vanilla\" R, not radian etc.!
- `r.rterm.windows`
  > R path for interactive terminals (Windows). Can also be radian etc.

**Comment by jjallaire** [comment]
The setting we are looking for definitely shouldn't be radian (as we'll also be forwarding this path along to knit) so I think the `r.rpath` is probably correct for our purposes.

**Comment by jjallaire** [comment]
@Fred-Wu I don't know what's going on here then -- what is the value of the `QUARTO_R` environment variable in your R child process / terminal?

**Comment by Fred-Wu** [comment]
How can I obtain `QUARTO_R` env variable? Is that under `Sys.getenv()`?

**Comment by danieltomasz** [comment]
I had the same error, I get the working path from this command inside R
```r
file.path(R.home("bin"), "R")
```

the system path didn't work for me

**Comment by jjallaire** [comment]
@Fred-Wu Yes if you have set `r.rpath.windows` then that will be propagated to Quarto as `QUARTO_R` and that's the version of R we will attempt to use.

All of that said, I think your R configuration needs some pruning as if you look in your diagnostic you'll see that you have lib paths from two different versions of R in play:

```
R installation:
  Version: 4.1.3
  Path: C:/PROGRA~1/R/R-41~1.3
  LibPaths:
    - C:/Users/xxxxxx/AppData/Local/R/win-library/4.2
    - C:/Program Files/R/R-4.1.3/library
  rmarkdown: (None)
```

This will never end well! Somewhere in your environment there are likely some variables set that are injecting additional lib paths (you should look at all environment variables in your shell and/or set for the user or system).

**Comment by Fred-Wu** [comment]
1. I cannot see `QUARTO_R` from `Sys.getenv()`
2. The error points to the user library for R4.2, which is the version I am using, and should be used by Quarto as well. 
However the error points to the system library for R4.1, but not the user library for this version.  
Both versions of R have user libraries, which could be identified correctly by RStudio. They are default during the installation. 

R4.1.3
```
> .libPaths()
[1] "C:/Users/xxxxxx/Documents/R/win-library/4.1" "C:/Program Files/R/R-4.1.3/library"     
```

R4.2.1
```
> .libPaths()
[1] "C:/Users/xxxxxx/AppData/Local/R/win-library/4.2"
[2] "C:/Program Files/R/R-4.2.1/library"
```

I installed R 4.1.3 later than R 4.2 because it is the version used by our internal shiny server, so have to develop the app using that version.  So it might overwrite the sys registry, R 4.1.3 is above R 4.2.1. 
Could this be the reason that Quarto somehow reads the system registry?

![image](https://user-images.githubusercontent.com/4111978/200241310-25aef874-e108-4159-8e1c-acbec4fbf5ee.png)

**Comment by Fred-Wu** [comment]
I have manually included the R version path to the Windows environment variable `PATH` for both user and system. 
The `quarto_render` now works. Otherwise `quarto check` in the terminal still also points to R4.1.3. 

So I think it may not be the issue of quarto-vscode.
