### ISSUE TITLE
Executing code blocks as one entity instead of line by line with with Cmd + Enter in VS Code

### ISSUE THREAD

**Issue by rappster** [quarto-dev/quarto-vscode#108]
First of: thanks a lot for creating quarto! It really rocks!

I have a little problem with executing entire code blocks (as opposed to "line by line" execution) in VS Code.

Let's take the following code block:

```
foo <- function() {
    "hello world"
}
```

In R Markdown documents, hitting `Cmd + Enter` will execute the code block in one go.

In Quarto documents, hitting `Cmd + Enter` will take me through the block line by line - which is kind of cumbersome.

I know that I can execute entire code cells with `Shift + Cmd + Enter` but I prefer to "step through my cells" block by block. 

Also don't know if this is a bug or a feature but if it's a feature: is there a way to change the execution behavior in some setting?

# My setup
- VS Code: v1.72
- [VS Code extension for R](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r): v2.6.1
- [VS Code extension for Quarto](https://marketplace.visualstudio.com/items?itemName=quarto.quarto): v1.53.0 
- R v4.2.1

# Additional context
I also recorded a short [Loom video](https://www.loom.com/share/a6ed2b9c505e466894057bd74c9f15db) that shows the difference between `.rmd` and `.qmd` files

**Comment by jjallaire** [comment]
Thanks for reporting this and especially thanks for the video outlining the issue and desired behavior! We have managed to make this work in the following commit: https://github.com/quarto-dev/quarto-vscode/commit/0ac9f340a5cf1b9af10aecc097601fb27a98f034

This is available now in v1.54.0 of the Quarto VS Code extension.

**Comment by rappster** [comment]
Thanks for the quick fix! Works like a charm now :-)
