### ISSUE TITLE
Intellij Idea Plugin

### ISSUE THREAD

**Issue by databill86** [quarto-dev/quarto-vscode#109]
Hello,

Thank you for this extension. 

Actually, this is not an issue.
Is there any plan to make a plugin for Intellij Idea, it would be really useful. 

Thank you!

**Comment by jjallaire** [comment]
We are eventually going to create a Quarto LSP which would make it pretty easy for either us or someone else to create an IntelliJ plugin. Not sure of the timing of that though.
