### ISSUE TITLE
Reference is improperly inserted in autocomplete feature

### ISSUE THREAD

**Issue by fuhrmanator** [quarto-dev/quarto-vscode#118]
This is related to another bug about the `-` separator between label prefixes, but I searched and couldn't find it (either in the cli Q&A or the issues of quarto-cli or quarto-vscode - my apologies).

When I type `@fig-` I get a list of items. If I select one of them, e.g., `fig-abc`, my text ends up with `fig-fig-abc`. This seems to be caused by the fact that the `-` de-activates the matching.

Here's what I see by just typing `@fig`

![image](https://user-images.githubusercontent.com/7606540/201149193-dcf119d3-bef6-4e84-8600-353cafb31398.png)

and after I add the `-`:

![image](https://user-images.githubusercontent.com/7606540/201149321-a46cc6b1-f951-42d7-9d78-c0bbafe87493.png)

and after selecting the first entry:

![image](https://user-images.githubusercontent.com/7606540/201149847-891b7a3d-c49b-4478-80b3-9a7eeb15268a.png)

**Comment by kompre** [comment]
I got a similar issue, but with any python autocompletion that I mentioned [here](https://github.com/quarto-dev/quarto-vscode/issues/111#issue-1433878514) (no response so far)

I've also tried what you mentioned and can confirm the same behavior.

**Comment by fuhrmanator** [comment]
Interesting @kompre. The workaround in my case is not to type `-`, but it doesn't look like that would help in your case.

**Comment by kompre** [comment]
> The workaround in my case is not to type `-`

It is the same for me.

Do you have problems also with python autocompletion lime I do? I wonder if is the same issue or two similar, but unrelated.

I was thinking about using a .ipynb directly because there python autocompletion works fine, 
but then I'll be missing all the **quarto** related auto-completion.

**Comment by jjallaire** [comment]
Thanks for reporting this! Fix is here (https://github.com/quarto-dev/quarto-vscode/commit/5ed057cc2dbb22a91c4adb95ea28581e8070baf7) and is available in the updated 1.55.0 release.

**Comment by fuhrmanator** [comment]
@jjallaire I confirm it's working - you guys are awesome to fix these so fast!
