### ISSUE TITLE
Markdown code in qmd file is not highlighted in vscode 

### ISSUE THREAD

**Issue by byryepez** [quarto-dev/quarto-vscode#121]
Hi..

I noticed that the markdown parts (headers, **bold**, _italic_, `inline code`, etc.) in a qmd document are not highlighted correctly when I open the file in vscode, while the same parts are highlighted in Rstudio. See images below. The opposite happens with Latex code (`$...$` or `$$ .. $$`, visible in vscode, but not in Rstudio). Is there a way to utilize several formatters at the same time in vscode, so both markdown and latex codes are highlighted?? 

![Quarto_vscode](https://user-images.githubusercontent.com/4457757/202589009-073fe9d9-9e04-44b5-af2f-2ce311ac9832.png)
![Quarto_Rstudio](https://user-images.githubusercontent.com/4457757/202589013-f7d9d0a9-81ae-42bf-a3b4-0c182f1045da.png)

I'm using vscode 1.73.1, quarto 1.2.269, quarto-vscode 1.55.0

**Comment by jjallaire** [comment]
The markdown is indeed highlighted in VS Code. Here is what I see w/ all the same versions of things:

<img width="575" alt="Screen Shot 2022-11-17 at 9 28 11 PM" src="https://user-images.githubusercontent.com/104391/202602898-8e4050d5-cadd-4731-b0f6-8eb22190bf39.png">

This is likely a result of the VS Code theme and/or syntax highlighting theme you are using.

**Comment by byryepez** [comment]
Hello ! thanks @jjallaire for answering. I have similar results as yours when I work with a rmd file:

![image](https://user-images.githubusercontent.com/4457757/202607899-65c63845-232f-4528-b2a4-b7edc6a0c5d3.png)

and also works with a md file:

![image](https://user-images.githubusercontent.com/4457757/202608676-f3f9c2bd-ad65-47ca-a4de-5c62b72a7396.png)

Could you please tell me which theme do you use, so I can compare? Is there an specific `editor.defaultFormatter` should I use in the `settings.json` file for that? Thanks!
