### ISSUE TITLE
When no jupyter kernel is specified  random kernel is tried when rendered

### ISSUE THREAD

**Issue by danieltomasz** [quarto-dev/quarto-vscode#13]
I have a document (ticks for code where removed)

```
---
title: "Untitled"
format: html
---

{python}
#| echo: fenced
import numpy
```

When I tried to render it, it uses  it tries to run a specific kernel in my case 'cognitive-reserve-3.9.10`, this  kernel doesn't exist, error is thrown
```
[Errno 2] No such file or directory: '/Users/daniel/.pyenv/versions/cognitive-reserve-3.9.10/bin/python'
```

I specified existing kernel in yaml
```
jupyter: cognitive-reserve-3.10.4
```

I sucesfully rendered the code.
Then I removed the kernel specification from the yaml.

When I tried to render code again,  the `cognitive-reserve-3.9.10` was tried to run.
The cognitive-reserve-3.9.10 was deleted a few weeks ago by me before  I installed quarto. 

Expectation:
- Either run  the kernel that was last used (if the plugin stores such data), in that case, `cognitive-reserve-3.10.4`
- Or throw an error that kernel isn't specified in YAML

**Comment by jjallaire** [comment]
There is probably some configuration somewhere that indicates that this kernel is still on your system (and you may need to purge that configuration). If you execute `quarto check` you'll see all of the kernels visible to quarto.

**Comment by danieltomasz** [comment]
interesting, the kernel is visible in `jupyter lab` and `quarto check` , but it is not visible with  `jupyter kernelspec list`
Still I would expect quarto to be explicit about kernel choice (but it might differ for others)


Now I know this, so this is not a problem for me, but might be confusing for  new users of Python  or quarto ecosystem

**Comment by jjallaire** [comment]
Hmm...so are you saying that if we called `jupyter kernelspec list` rather than doing our own detection that the behavior would be as-intended? That might be the right thing for us do -- currently we read the JSON files directly to save 500ms but if that's leading to detecting incorrect kernels its not worth it.

**Comment by danieltomasz** [comment]
sorry for confusion, those kernels existed in the  `jupyter kernelspec list`, but they were just aliases created by vscode to kernels I deleted 

What I meant would be to force users to  explicitly specify kernel in YAML (locally) or in quarto-plugin in vscode settings via settings.json (globally)

When I dont specify  kernel  in yaml, but the chosen by quarto kernel exist the output doesnt show what kernel quarto is using
```
> /Applications/quarto/bin/quarto preview test.qmd--no-browser--no-watch-inputs
Done
Executing 'test. ipynb'
Cell 1/1... Done
pandoc
to: html
output-file: test.html
standalone: true
section-divs: true
html-math-method: mathjax
wrap: none
default-image-extension: png
filters:
crossref
metadata
document-css: false
link-citations: true
date-format: long
lang: en
title: Untitled
Output created: test.html
Watching files for changes
Browse at http://localhost:3784/
```
Printing kernel name in such case might reduce confusion

**Comment by jjallaire** [comment]
Okay, we now print the name of the kernel in our "Starting" message. So where we used to print:

```
Starting Jupyter kernel...
```

We now print e.g:

```
Starting cognitive-reserve-3.10.4 kernel...
```

LMK if this sounds like a good resolution as well as anything else you think would be helpful for this scenario.

**Comment by danieltomasz** [comment]
I think this the best solution...
It's doesnt change current default
My first solution to force users to specify kernel might be really bad for portability/colaboration issues...

Prinitng which kernel is used might be enough information to debug  in case of problems/wrong kernel...

Thank you, this issue might be closed I think :)

**Comment by jjallaire** [comment]
Okay, thanks again for reporting and following up on the discussion!
