### ISSUE TITLE
The R extention's ID has been changed

### ISSUE THREAD

**Issue by eitsupi** [quarto-dev/quarto-vscode#14]
See https://github.com/REditorSupport/vscode-R/issues/690#issuecomment-1115829408

The ID of the R extension is hard-coded in the following places, but it seems to be working even after changing the ID.

https://github.com/quarto-dev/quarto-vscode/blob/6ee938694ea08a49f101f56069c9cb0f27964d54/src/providers/cell/executors.ts#L158

@isidorn Do you know if we should update the IDs in the source code?

**Comment by isidorn** [comment]
Not sure. But I think it would not hurt. So I suggest to update it.

**Comment by jjallaire** [comment]
It looks like we are still working because the package.json of the R extension still uses the old name and publisher:

https://github.com/REditorSupport/vscode-R/blob/master/package.json#L1-L9

Assuming this will ultimately be changed? In that case I'll make sure we can handle either.

**Comment by isidorn** [comment]
Yes, that should change.

**Comment by eitsupi** [comment]
It may change the next release REditorSupport/vscode-R#1093

@renkun-ken Any plans for the next release? (I know you used to release them monthly, but has it been a while?)

**Comment by renkun-ken** [comment]
Too busy these weeks. I'll probably make a release in a few days.

**Comment by eitsupi** [comment]
Thanks all!
It seems be resolved by 260c581e25da5d9941e70271052acb6755cf9fbc, so I close this.
