### ISSUE TITLE
Chunk options on first-line not recognized as executable code chunk

### ISSUE THREAD

**Issue by Lightbridge-KS** [quarto-dev/quarto-vscode#17]
Hi, May I suggest some improvements.

I've found that R code chunk that has options defined on the **first line** or has **space** after `r` can't be recognized as executable code chunk, and the code can't be run (by cmd-enter). 

<img width="351" alt="Screen Shot 2565-05-08 at 21 47 05" src="https://user-images.githubusercontent.com/67057499/167301741-11b2b82d-4a0c-4c3e-a2d3-9bcc55134d5f.png">

(This works fine in RStudio, however.)

I've notice that you recommend using the comment-based syntax, however, may be someone (including me) might use in-line option in some chunk, also.

I guess, the problem might located in the regular expression somewhere that matching code chunk.

However, This is a Great extension thus far, Good job 👍 

Thankyou

**Comment by jjallaire** [comment]
Thanks for pointing this out! I made the change to do more liberal parsing here: https://github.com/quarto-dev/quarto-vscode/commit/169c5cda0fb146ae1410b5d64e9bb439052245ce

This will be in the next release which should be in ~ 1 week or so.

**Comment by Lightbridge-KS** [comment]
Thank you !
