### ISSUE TITLE
Autcomplete citations

### ISSUE THREAD

**Issue by atomashevic** [quarto-dev/quarto-vscode#18]
Autocompletion of citations (and other references) after hitting `@` would be a great feature for the extension.

[Pandoc Citer](https://marketplace.visualstudio.com/items?itemName=notZaki.pandocciter) does the similar thing for regular `.md` documents but it currently does not support `.qmd` and requires that bib file is specified between squred brackets in YAML (`bibliography: [path/to/.bib]`)

**Comment by jjallaire** [comment]
Yes, this is definitely something we'd like to do soon!

**Comment by danieltomasz** [comment]
`LateX Workshop` has a really nice citation picker/browser too.

**Comment by atomashevic** [comment]
[Pandoc Citer](https://marketplace.visualstudio.com/items?itemName=notZaki.pandocciter) has included `.qmd` files and now it works OK as long as you but `.bib` file in square brackets in YAML.

Here's some screenshots. Content is not in English but you can get the gist of it:

![vscode2](https://user-images.githubusercontent.com/39856297/169660389-842202c3-c694-438e-bc99-6d9fe2619ee9.png)
![vscode1](https://user-images.githubusercontent.com/39856297/169660391-c5ca24a2-f065-48e6-8b67-155a9c7272d8.png)
