### ISSUE TITLE
`quarto` is not started at root directory, thus no `renv`

### ISSUE THREAD

**Issue by mcanouil** [quarto-dev/quarto-vscode#19]
Related to quarto-dev/quarto-cli#855

It appears, the extension for VSCode executes `quarto` from the directory of the `.qmd` file thus `renv` is not accessed since at project's root.
The same behaviour might also be in RStudio, but I dit not check.

## Setup project

```sh
R -q -e 'renv::init()'
```

<details><summary>See output</summary>

```sh
#> * Initializing project ...
#> * Discovering package dependencies ... Done!
#> * Copying packages into the cache ... Done!
#> The following package(s) will be updated in the lockfile:
#> 
#> # CRAN ===============================
#> - renv   [* -> 0.15.4]
#> 
#> * Lockfile written to '~/Projects/misc/renv.lock'.
#> * Project '~/Projects/misc' loaded. [renv 0.15.4]
```

</details>

```sh
R -q -e 'renv::install("ggdist")'
```

<details><summary>See output</summary>

```sh
#> Installing HDInterval [0.2.2] ...
#>         OK [linked cache]
#> Installing numDeriv [2016.8-1.1] ...
#>         OK [linked cache]
#> Installing distributional [0.3.0] ...
#>         OK [linked cache]
#> Installing ggdist [3.1.1] ...
#>         OK [linked cache]
```

</details>

```sh
Rscript -q -e 'writeLines("---\nformat:\n  html:\n    self-contained: true\n---\n\n```{r}\nlibrary(ggdist)\n```\n", "test.qmd")'ined: true)
mkdir subdir
Rscript -e 'writeLines("---\nformat:\n  html:\n    self-contained: true\n---\n\n```{r}\nlibrary(ggdist)\n```\n", "subdir/test.qmd")'
```

### [Success] Render qmd in project's root

```sh
quarto render test.qmd
```

<details><summary>See output</summary>

```sh
#> processing file: test.rmarkdown
#>   |.......................                                               |  33%
#>   ordinary text without R code
#> 
#>   |...............................................                       |  67%
#> label: unnamed-chunk-1
#>   |......................................................................| 100%
#>   ordinary text without R code
#> 
#> 
#> output file: test.knit.md
#> 
#> pandoc 
#>   to: html
#>   output-file: test.html
#>   standalone: true
#>   self-contained: true
#>   section-divs: true
#>   html-math-method: mathjax
#>   wrap: none
#>   default-image-extension: png
#>   filters:
#>     - crossref
#>   
#> metadata
#>   document-css: false
#>   link-citations: true
#>   date-format: long
#>   lang: en
#>   
#> Output created: test.html
```

</details>

### [Success] Render qmd in a subdirectory of project's root

```sh
quarto render subdir/test.qmd
```

<details><summary>See output</summary>

```sh
#> processing file: test.rmarkdown
#>   |.......................                                               |  33%
#>   ordinary text without R code
#> 
#>   |...............................................                       |  67%
#> label: unnamed-chunk-1
#>   |......................................................................| 100%
#>   ordinary text without R code
#> 
#> 
#> output file: test.knit.md
#> 
#> pandoc 
#>   to: html
#>   output-file: test.html
#>   standalone: true
#>   self-contained: true
#>   section-divs: true
#>   html-math-method: mathjax
#>   wrap: none
#>   default-image-extension: png
#>   filters:
#>     - crossref
#>   
#> metadata
#>   document-css: false
#>   link-citations: true
#>   date-format: long
#>   lang: en
#>   
#> Output created: test.html
#> 
```

</details>

## Render using `quarto-vscode`

```sh
code .
```

### [Success] Render "test.qmd" via `quarto-vscode` extension "button".

<details><summary>See output</summary>

#> /Applications/quarto/bin/quarto preview test.qmd --no-browser --no-watch-inputs
#> 
#> 
#> processing file: test.rmarkdown
#>   |.......................                                               |  33%
#>   ordinary text without R code
#> 
#>   |...............................................                       |  67%
#> label: unnamed-chunk-1
#>   |......................................................................| 100%
#>   ordinary text without R code
#> 
#> 
#> output file: test.knit.md
#> 
#> pandoc 
#>   to: html
#>   output-file: test.html
#>   standalone: true
#>   self-contained: true
#>   section-divs: true
#>   html-math-method: mathjax
#>   wrap: none
#>   default-image-extension: png
#>   filters:
#>     - crossref
#>   
#> metadata
#>   document-css: false
#>   link-citations: true
#>   date-format: long
#>   lang: en
#>   
#> Output created: test.html
#> 
#> Watching files for changes
#> Browse at http://localhost:5728/

</details>

### [Failure] Render "subdir/test.qmd" via `quarto-vscode` extension "button".

<details><summary>See output</summary>

#> /Applications/quarto/bin/quarto preview test.qmd --no-browser --no-watch-inputs
#> 
#> 
#> processing file: test.rmarkdown
#>   |.......................                                               |  33%
#>   ordinary text without R code
#> 
#>   |...............................................                       |  67%
#> label: unnamed-chunk-1
#> Quitting from lines 8-9 (test.rmarkdown) 
#> Error in library(ggdist) : there is no package called 'ggdist'
#> Calls: .main ... withVisible -> eval_with_user_handlers -> eval -> eval -> library
#> 
#> Execution halted

</details>

## `quarto`

```sh
quarto --version
#> 0.9.399
```

**Comment by jjallaire** [comment]
We just made a change in our vscode extension (released yesterday) to start from the project dir: https://github.com/quarto-dev/quarto-vscode/commit/00c5382fd4591ed9966bb478ecdcf0679ab7e351

If you update the extension does the behavior change?

**Comment by mcanouil** [comment]
I am using `v1.20.1`, is there another version?
<img width="621" alt="image" src="https://user-images.githubusercontent.com/8896044/168439632-9cd8f6f3-acb4-4dbf-876e-1f7086756e1d.png">

**Comment by jjallaire** [comment]
That is the right version! Could you send me a link to a git repo where this repros and I'll run it down.

**Comment by mcanouil** [comment]
Here it is: https://github.com/mcanouil/quarto-renv

**Comment by jjallaire** [comment]
It looks like the problem is that there is no `_quarto.yml` file at the root so neither quarto nor vscode knows to use that root as the source of a possible venv (we don't just chase up the directory structure looking for an renv, we need some other "tell" to indicate we should use it).

So adding a project file at the root definitely solves the problem for vscode. With this commit (https://github.com/quarto-dev/quarto-cli/commit/f82b3d93d3340cae1d952574d481e31fb0708736, avail in release v0.9.403) this is as simple as just `touch _quarto.yml` in the root directory (previously you needed to actually have some yaml in there, but there is no reason that the mere existence of the file shouldn't imply a project).

All of that said, I think our vscode extension should also be running the `.qmd` files from the workspace root in the case that there isn't a project (which should fix the problem even w/o the `_quarto.yml`). I'll work on that next.

**Comment by jjallaire** [comment]
Here is the related fix in quarto-vscode: https://github.com/quarto-dev/quarto-vscode/commit/76ba6f454026f5a2debd98013284f47fdda10f5b

This will ship w/ the next extension release (probably a few days)

**Comment by mcanouil** [comment]
Thank, I'll check both cli and vscode extension when released.
