### ISSUE TITLE
Math Highlighting is Buggy

### ISSUE THREAD

**Issue by MatrixRanger98** [quarto-dev/quarto-vscode#24]
Math highlighting is very buggy.

![image](https://user-images.githubusercontent.com/48684632/169874431-11589643-48a2-4889-832c-c29631e76707.png)

**Comment by MatrixRanger98** [comment]
In fact, if you check README.md, the math syntax highlighting is incorrect even in the demo.

![image](https://user-images.githubusercontent.com/48684632/169874825-1c5bce3f-efb7-4ae1-a83b-30ccf896907b.png)

**Comment by jjallaire** [comment]
Thanks for reporting this. I think this has something to do with how we are embedding the math rules. I will take a closer look at this later on this week.

**Comment by jjallaire** [comment]
Okay, this is now resolved in v1.22.0. Thanks again for reporting!
