### ISSUE TITLE
Temporary intellisense.py shows up in "Problems" panel

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto-vscode#26]
I'm not 100% sure if this is related to the Quarto extension, but this only occurs in my Quarto projects. Sometimes, the "Problems" panel contains linting warnings for a file called "intellisense.py", which is not part of my project but in some /var/... directory. It seems like this is some temporary file used to run code cells, so it should not be part of the project (and therefore, no problems should be reported).

I just wanted to report the actual file location and contents, but the problems disappeared right now. I still wanted to leave this report here just in case someone else has also noticed this. I will come back and add more details when this appears again.

**Comment by cbrnr** [comment]
OK, it appeared again, here's a screenshot:
![Screen Shot 2022-05-27 at 11 26 40](https://user-images.githubusercontent.com/4377312/170672035-c49f6cf9-0ac5-4a59-b735-9ff9818cbeb2.png)

And here's the content of this file:

<details>

```
# type: ignore























































































import pandas as pd







import numpy as np

data = np.arange(1, 21).reshape((4, 5))
pd.DataFrame(data)







pd.DataFrame(data, columns=["A", "B", "C", "D", "E"])








pd.DataFrame({"A": [1., 2, 3, 4], "B": ["w", "x", "y", "z"], "C": np.arange(4)})












pd.DataFrame.from_dict({1: [1, "a", 3, 5.], 2: [2, "b", 4, 6.]}, orient="index")








df = pd.DataFrame(
    {"A": [1., 2, 3, 4], "B": ["w", "x", "y", "z"], "C": np.arange(4)}
)
df



















import pandas as pd

flights = pd.read_csv("flights.zip")
flights.info()





```

</details>

**Comment by jjallaire** [comment]
This is indeed a file we create for embedded completions in Python cells. The `#type: ignore` is there to make sure that pyright ignores the file, but it looks like you have a tool called `flake8` reporting problems -- do you know if there is a comment/annotation we can add to the file to ignore flake8 errors?

**Comment by cbrnr** [comment]
Yes, `# flake8: noqa` at the top of the file should do the trick.

**Comment by jjallaire** [comment]
Okay, this should fix the issue then: https://github.com/quarto-dev/quarto-vscode/commit/7e65e17c083e217131742113aca53656ab578707

**Comment by kjelljorner** [comment]
This seems to happen as well with [isort](https://github.com/PyCQA/isort) ([vscode extension](https://github.com/microsoft/vscode-isort)). They have some [options](https://github.com/PyCQA/isort#skip-processing-of-imports-outside-of-configuration) for skipping.
