### ISSUE TITLE
Copying text from Quarto Preview window?

### ISSUE THREAD

**Issue by cbrnr** [quarto-dev/quarto-vscode#27]
I just tried to select and copy text from a Quarto Preview window (<kbd>⌘</kbd><kbd>c</kbd>), but it seems like this doesn't work. Is this an intentional decision? If not, I think it would be very useful!

**Comment by cbrnr** [comment]
It is probably because *all* keyboard shortcuts are disabled when this viewer is in focus (there's a small "Focus Lock" text appearing at the bottom). This means that e.g. <kbd>⌘</kbd><kbd>shift</kbd><kbd>p</kbd> (the command palette) doesn't work, which I use all the time to do almost everything. Not sure if this is a good idea, but maybe there are good reasons for this?

**Comment by jjallaire** [comment]
I believe we need to implement a workaround like the one described here: https://github.com/microsoft/vscode/issues/65452#issuecomment-586485815

**Comment by jjallaire** [comment]
No, we can't use the integrated previewer (that actually deals w/ live-rendering raw markdown -- and it doesn't know how to render pandoc markdown or quarto extensions, not even to speak of dealing w executable cells). It will be very easy to implement this workaround in our viewer.

**Comment by jjallaire** [comment]
Okay, I've got this all working as expected now (clipboard operations as well as other commands all work when focus is within the preview). Updates to both the very latest Quarto CLI (v0.9.479) as well as the very latest VS Code Extension (v1.23.0) are required for this fix.

**Comment by cbrnr** [comment]
Great work! I just tested this and indeed copying text (and other shortcuts) work. Two minor suggestions that would improve consistency:

1. A context menu when right-clicking with a "Copy ⌘C" entry would be helpful.
2. The small "Focus Lock" banner at the bottom of the preview should be removed if possible.

Again, these are just things that would be nice to have (and maybe you disagree) – it already works very nicely with your latest changes! Thank you for dealing with these things so quickly! I really love working with Quarto from VS Code!

**Comment by jjallaire** [comment]
Thanks for the additional feedback -- I got rid of the 'Focus Lock' indicator. Unfortunately the context menu I seem to have less control over (will keep trying to sort that out though).
