### ISSUE TITLE
Quarto installation not found on Linux VSCode extension

### ISSUE THREAD

**Issue by slwu89** [quarto-dev/quarto-vscode#28]
Hi Quarto team,

I'm trying to use Quarto on Pop!_OS 22.04 LTS on Visual Studio Code 1.67.2. I have Quarto 0.9.505 installed (pasting results from `quarto check` below). When I try to render in VSCode using the Quarto extension on a .qmd file I get the error box "Please install the Quarto CLI before rendering documents", but it is already installed. I've also gone through a computer reset.

```
[✓] Checking Quarto installation......OK
      Version: 0.9.505
      Path: /opt/quarto/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.4
      Path: /usr/bin/python3
      Jupyter: 4.10.0
      Kernels: julia-1.7, python3

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.1.2
      Path: /usr/lib/R
      LibPaths:
        - /home/slwu89/R/x86_64-pc-linux-gnu-library/4.1
        - /usr/local/lib/R/site-library
        - /usr/lib/R/site-library
        - /usr/lib/R/library
      rmarkdown: 2.14

[✓] Checking Knitr engine render......OK
```

**Comment by slwu89** [comment]
I've checked that using `quarto render test.qmd --to html` on a test file works, so the CLI is working as expected.

**Comment by jjallaire** [comment]
We attempt to execute quarto using whatever PATH is available inside VS Code. For whatever reason VS Code isn't seeing the /opt/quarto/bin directory (can't say why). If you go into settings there is a `quarto.path` setting that you can provide to make this explicit.

**Comment by slwu89** [comment]
Thanks for the help @jjallaire! I've tried adding that to the settings and I'm still getting the same issue.
![image](https://user-images.githubusercontent.com/10673535/171919585-503f5f80-81fd-480b-852b-6b67d3782be2.png)

**Comment by jjallaire** [comment]
I think you need to it to /opt/quarto/bin/quarto

**Comment by slwu89** [comment]
Thanks! Problem solved.
