### ISSUE TITLE
Allow user to toggle `--no-watch-inputs` flag when running Quarto Render

### ISSUE THREAD

**Issue by ddanieltan** [quarto-dev/quarto-vscode#32]
The default behavior for Quarto Render runs `/Applications/quarto/bin/quarto preview welcome.qmd --no-browser --no-watch-inputs`. I find it strange that the default command includes the `--no-watch-inputs` flag and suggest adding the ability to toggle the flag off.

**Comment by ddanieltan** [comment]
Thanks for keeping this issue open! I saw a very similar issue raised here: https://github.com/quarto-dev/quarto-vscode/issues/6, and I think it's valuable to have future users be able to discover the existing conversation + the team's thoughts behind rendering on save.

**Comment by fuhrmanator** [comment]
It's even more confusing (to me) because (in Windows, inside a bash) there's a console message:

```
...

Watching files for changes
Browse at http://localhost:7619/
```

It implies it should see the changes when one saves. If I re-run the command without `--no-watch-inputs` the message is the same and changes are detected.

Knowing about <kbd>ctrl</kbd>-<kbd>shift</kbd><kbd>k</kbd>, it now makes more sense (but it's not intuitive to me).

**Comment by fuhrmanator** [comment]
> Knowing about <kbd>ctrl</kbd>-<kbd>shift</kbd><kbd>k</kbd>, it now makes more sense (but it's not intuitive to me).

Oh, wow, I realize now that using this command in a reveal.js document causes the slide where your cursor is to in the preview inside VSCode. Very cool! I'm loving Quarto more every day!

**Comment by alexkyllo** [comment]
This confused me too, the console message literally says "Watching files for changes" even though it isn't doing that.

I would really like to have two commands in the extension--say "Quarto: Render" (current behavior) and "Quarto: Render and Watch," would call `quarto `preview` without and with the `--no-watch-inputs` option, respectively. Then I can decide if I want rendering on save or not.

**Comment by Victor-Botelho** [comment]
How can I use the render button in VSCode without passing the `--no-watch-inputs` flag?

**Comment by jjallaire** [comment]
That option is really saying "don't watch the inputs b/c the editing environment will take care of that". Unfortunately in VS Code we didn't (until now) have a way to specify "Render on Save" as we do in RStudio. With the release of v1.36.0 of the extension there is now a **Render on Save** option, and you can also specify the same behavior per-document or per-project in YAML (for sharing configuration across editors). Here is the documentation:

https://quarto.org/docs/tools/vscode.html#render-on-save

Note also that even though we aren't "watching inputs" we are in fact "watching files for changes" (those files being configuration and CSS files that might require a refresh).
