### ISSUE TITLE
Pylance integration

### ISSUE THREAD

**Issue by MathieuMarauri** [quarto-dev/quarto-vscode#33]
Hello, 

The code in cell blocks in qmd file is not checked as it would be in Jupyter notebook cells by Pylance. A simple example is trying to import a library not installed in the virtual env: 

* In a Jupyter notebook it will be underlined to show that the library is not available
<img width="201" alt="Screenshot 2022-06-23 at 16 45 06" src="https://user-images.githubusercontent.com/11965307/175327434-2b2e4830-b743-408c-8281-a19ef74cc1c7.png">

* In a qmd file nothing is displayed 
<img width="183" alt="Screenshot 2022-06-23 at 16 45 21" src="https://user-images.githubusercontent.com/11965307/175327396-c2ecff9e-9258-4eb7-8ddf-f09fd440e831.png">

How can I make Pylance (or something else) integrate with the Quarto extension?

Thanks,
Mathieu

**Comment by jjallaire** [comment]
This is something we'd definitely like to get working but haven't had the time to yet (there is some trickiness around creating temporary .py files for pylance to process and not have those files also show up in the user's workspace)

**Comment by Bonnevie** [comment]
@jjallaire do you know if this is related to the issues with autocomplete #10 given that Pylance is the default autocomplete engine in VS Code?

**Comment by jjallaire** [comment]
No it's not related to issues with autocomplete. This is b/c the underlying source file being checked is a temporary .py file (so the links to problems end up being wrong and the temporary file ends up displaying in an editor tab).
