### ISSUE TITLE
YAML value ... must be a Quarto YAML front matter object.

### ISSUE THREAD

**Issue by albert-ying** [quarto-dev/quarto-vscode#37]
Hi, I use the HTML syntax to insert the image to the slide. It works fine, but the quarto sometime shows it as a problem (although it would render just fine). I'm wondering how can I disable this warning?

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/59846322/178074969-ab524679-c1dd-4310-b40e-2731d91d1552.png">

**Comment by jjallaire** [comment]
Could you share a more complete example with a document that exhibits this warning reproducibly?

**Comment by albert-ying** [comment]
```
---
title: "Untitled"
format: revealjs
---

---

<img src="
https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
alt="Google Logo">

---

<img src="
https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
alt="Google Logo">



```

This is the minimal reproducible example: you will see the first image
shows problem.

Thank you!

Best,
Albert

**Comment by jjallaire** [comment]
Thanks! I believe that we fixed this bug in quarto-cli a few days ago: https://github.com/quarto-dev/quarto-cli/commit/c8ec3f8f3dd494c8f177830e91019b9f5507b075

Try updating to the very latest Quarto (v1.0.5) and things should work as expected.
