### ISSUE TITLE
Can render quarto doc in RStudio but not in VSCode

### ISSUE THREAD

**Issue by werkstattcodes** [quarto-dev/quarto-vscode#38]
In a .qmd (Quarto) document calling the library(treemapify) works. I can run the code chunk without problem.
However, when rendering the document to html I get the prompt:

```
Error in library(treemapify) : there is no package called 'treemapify'
Calls: .main ... withCallingHandlers -> withVisible -> eval -> eval -> library
Execution halted
```

Rendering the same file in RStudio does not produce the error.

**To Reproduce**
Create the .qmd (Quarto) file with the content below.

```{r}
library(tidyverse)
library(treemapify)
find.package("tidyverse")
find.package("treemapify")
```

Assuming that `treemapify `has been already [installed](https://github.com/wilkox/treemapify), run the code chunk. (No issue).
Render the document. Error. Issue appears.

Open the same document in RStudio and render it. No error occurs.

I use Quarto, R and VSCode without problem. Only with this package the strange error occurs.

**Comment by werkstattcodes** [comment]
As an update. I have now encountered the issue with 3 packages. Whenever I include one of those packages (with library) into the qmd script, I cannot render the document in VSCode, but in RStudio. I can run the chunk(s) in vscode, but not render the document.

---
title: "test_vscode_writexl"
format: html
---

```{r}
library(writexl)
library(summarytools)
library(treemapify)
```

**Comment by cderv** [comment]
For reference, discussion has been opened in https://github.com/quarto-dev/quarto-cli/discussions/1372

**Comment by werkstattcodes** [comment]
Issue solved here https://github.com/quarto-dev/quarto-cli/discussions/1372
