### ISSUE TITLE
Alignment of "Execute R code" keyboard shortcut with R extension

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto-vscode#41]
In the Quarto VSCode extension, [Cmd/Ctrl]+Enter executes the R code on the current selected or positioned lines of the document.

In the [R VScode extension](https://github.com/REditorSupport/vscode-R), the same shortcut executes the current selected _text_ if a selection is made, or otherwise the current statement (traversing both up and down to find the bounds of the current statement).

It'd be great if the Quarto VScode extensions' behaviour was adjusted to align with the R extension, so that there aren't differences depending on whether a user is editing an R script or a Quarto document. (I personally prefer the R extension's behaviour because it means you can do things like execute pipes while leaving the assignment off for exploration, but I accept that it's largely a matter of taste!).

**Comment by jjallaire** [comment]
Interesting. On the other side I think we'd want to take inventory of what the Python extension does as well as what RStudio does (which is I believe what our current behavior is based on). We'll dig further into this soon.

**Comment by jimjam-slam** [comment]
That's fair! Another option may be to expose commands for both to the extension API so that users can map the keys to their preference.

**Comment by eitsupi** [comment]
Related to #7

**Comment by MilesMcBain** [comment]
I just checked, and for pipe chains and function calls the behaviour of RStudio and the VSCode extension are identical.

CTRL + ENTER runs expression the cursor is on in the console, irrespective of where it is placed in that expression.

**Comment by jimjam-slam** [comment]
Not sure if this change was documented, but as of Quarto 1.1.251 and Quarto VSCode extension 1.54.0, Cmd+Enter now aligns with the R extension in VSCode, running:

* selected _text_ (rather than the whole lines) if text is selected, or
* the whole statement that the cursor is on if there is no text selected, traversing forward and backward

Thanks very much!
