### ISSUE TITLE
no module named 'nbformat

### ISSUE THREAD

**Issue by alunap** [quarto-dev/quarto-vscode#42]
No success using quarto within VS Code on OS X. I have tried it with python, julia, and R cells, but this makes no difference. In the terminal it opens I confirm that jupyter is installed (I used it all the time), as is the ipykernel 'julia-1.7' that I set in the yaml. 
I saw mention of disabling the setting Terminal>Integrated>Shell Integration. I turn off the checkbox (although it still says 'Enabled', the json says false).
Opening an ipynb in VS Code and running julia cells works fine.
the YAML ends with
jupyter: julia-1.7

From the terminal in vscode
% jupyter kernelspec list
Available kernels:
  ir                    /Users/alun/Library/Jupyter/kernels/ir
  javascript            /Users/alun/Library/Jupyter/kernels/javascript
  julia-1.7             /Users/alun/Library/Jupyter/kernels/julia-1.7
  python3               /Users/alun/opt/miniconda3/share/jupyter/kernels/python3
...

**Comment by GlekoMa** [comment]
I catched same error when run "quarto check".
I just run `pip install nbformat` then run 'pip install nbclient' and fixed it.
Did you have tried these? Hope helpful to you.
