### ISSUE TITLE
Cross-references auto-completion

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-vscode#43]
It would be great if `@` sign could trigger auto-suggestion for bibliography citation keys, and other prefixes, such as `@fig-`, `@tab-`, `@sec-`, etc, could contextually suggest available labels within the current document or project.

**Comment by jjallaire** [comment]
Yes, we are working on that right now here: https://github.com/quarto-dev/quarto-vscode/tree/feature/ref-completions

**Comment by jjallaire** [comment]
This is is now available in the latest release.
