### ISSUE TITLE
Clicking render in VS-code runs the cmd from incorrect directory

### ISSUE THREAD

**Issue by rl627** [quarto-dev/quarto-vscode#46]
When I click the Quarto render button in VS-code. It seems that the actual code being run in the terminal is incorrect. (see the snip below). 

![image](https://user-images.githubusercontent.com/45013044/181048800-4a65da87-de05-40aa-9c43-169774c7d786.png)

**Comment by jjallaire** [comment]
Thanks very much for reporting this! This has been resolved in v1.29.0 of the extension which has just been published to the marketplace.
