### ISSUE TITLE
Code blocks not showing or responding to Run commands

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto-vscode#5]
When I work with `.qmd` files in VSCode, code blocks are formatted as such with language-appropriate syntax highlighting, but they do not display Run cell/Run lines commands. If I press Cmd+Enter to run highlighted text, I get an error from the Quarto extension:

> Editor selection is not within an executable cell

![image](https://user-images.githubusercontent.com/6520659/158317315-40d8bf5a-ac59-4018-a888-ac19dbccf641.png)

Quarto extension version: 1.9.0
VSCode version: 1.65.2
OS: Darwin arm64 21.3.0

**Comment by jjallaire** [comment]
This is likely because the R and Python extensions aren't installed (or the requisite versions of them are not installed, the R extension in particular needs to be the version released last week).

I've just made a change to _always_ show the Run buttons and then on execution provide a message indicating that you don't have the required version of the given extension to run code cells: https://github.com/quarto-dev/quarto-vscode/commit/63a919fc9bc28492cdb8be70b0839a50625b289a

**Comment by jimjam-slam** [comment]
Mmm, interesting! I do have the extensions installed, but I don't go out of my way to keep them up to date (unless VSCode handles that). It looks like they meet the requirements in that commit you've reference, though:

Python extension version: v2022.2.1924087327 (15/03/2022)
R extension version: v2.4.0 (08/03/2022)

**Comment by jjallaire** [comment]
I see the problem now, it's the chunk labels you've included, e.g. ```` ```{r rtest} ````. That is valid in R Markdown but in Quarto the language stands by itself and the label is provided as a YAML option, e.g.

````
```{r}
#| label: rtest

```
````

That is the official, document Quarto syntax (and works for all engines including Knitr, Jupyter, and Observable). It so happens that since we use Knitr under the hood for R that the chunk labels as you wrote them above _will actually work_ (but that's more for backwards compatibility than as a by design going forward thing).

Our markdown parser in VS Code currently handles only the documented syntax. We could enhance it to handle Knitr style chunk labels but that's not how it works currently.

**Comment by jimjam-slam** [comment]
Ooooh. Yep, that does it!

I totally missed that in the docs and just kept using knitr chunk labels. Thanks for clarifying!
