### ISSUE TITLE
Shiny does not work in Preview

### ISSUE THREAD

**Issue by Fred-Wu** [quarto-dev/quarto-vscode#50]
I tried the Shiny example from the Guide. It worked on RStudio, but not VScode. 

Here is the output when rendering to `html`

<img width="573" alt="image" src="https://user-images.githubusercontent.com/4111978/183412610-f8d72e9f-00ed-47ed-9dd7-1e965a9d5e59.png">

**Comment by jjallaire** [comment]
VS Code extension doesn't currently know how to launch shiny interactive documents (we'll improve this soon!)

**Comment by jjallaire** [comment]
We just resolved this here: https://github.com/quarto-dev/quarto-vscode/commit/a0b5e2c0ecc13b79135954ac4942e9e651f87ff2 

This will be in the next release of the extension (within a couple of days)
