### ISSUE TITLE
Nested div blocks don't fold correctly.

### ISSUE THREAD

**Issue by nhz2** [quarto-dev/quarto-vscode#54]
Quarto supports nested div blocks, described in <https://pandoc.org/MANUAL.html#divs-and-spans>

For example the following renders as expected:

```qmd
# Nested callout

:::{.callout-note}

:::{.callout-note}

:::

:::{.callout-note}

:::

:::
```

![image](https://user-images.githubusercontent.com/39104088/183486011-c2b6b2d0-968f-4a2f-a69e-f3364cf7f53b.png)

However, in vscode, folding the top level div block doesn't hide both inner div blocks.

![image](https://user-images.githubusercontent.com/39104088/183486656-e006fffe-3683-4ed5-a7bf-8f3a2d572972.png)

I think if possible it should look like the following when the top level div is folded.

![image](https://user-images.githubusercontent.com/39104088/183487757-ec776606-6d84-4091-bbe0-ddd3529dec93.png)

**Comment by jjallaire** [comment]
If you use four colons for the outer div then this will work as expected:

````markdown
# Nested callout

:::{.callout-note}

:::{.callout-note}

:::

:::{.callout-note}

:::

:::
````

This limitation arises because the markdown parser we use in vscode (markdown-it) isn't fully Pandoc compatible so there will sometimes be small differences in behavior.
