### ISSUE TITLE
Behaviour of quarto.runSelection

### ISSUE THREAD

**Issue by ratnanil** [quarto-dev/quarto-vscode#55]
In \*.R and \*.Rmd files, I can place the cursor anywhere in a multiline statement, when hitting <kbd>Ctrl</kbd>+<kbd>Enter</kbd> VSCode will "*send the 'minimum bit of runnable code' to the console*" (see https://github.com/REditorSupport/vscode-R/issues/437#issuecomment-1003074628). 

So I can add this code to an \*.R and \*.Rmd file and no matter if I place the cursor on line 1 or 2 and hit <kbd>Ctrl</kbd>+<kbd>Enter</kbd> evaluate `head(mtcars)` correctly.

```{r}
mtcars  |>
    head()
``` 

However, this does not work with \*.qmd files. <kbd>Ctrl</kbd>+<kbd>Enter</kbd> only sends a *single* (the current) line to the terminal. Either line 1, whereas the terminal waits for further input, or line 2, where R complains that there is no default value to `x` in `head()`.

**Comment by ratnanil** [comment]
Possible duplicate of #41

**Comment by PMassicotte** [comment]
Have you tried to keymap it?
```json
{
    "key": "ctrl+enter",
    "command": "r.runSelection",
    "when": "editorTextFocus && editorLangId == quarto || editorLangId == r"
  }
```

**Comment by ravichowdhury88** [comment]
> Have you tried to keymap it?
> 
> ```json
> 
> {
> 
>     "key": "ctrl+enter",
> 
>     "command": "r.runSelection",
> 
>     "when": "editorTextFocus && editorLangId == quarto || editorLangId == r"
> 
>   }
> 
> ```

Can confirm that this solved the issue for me. Thank you!

**Comment by ratnanil** [comment]
Sorry for the delayed response. This solves the issue!

**Comment by ratnanil** [comment]
Just as an Info, after settings this keymap, I had to add the following keymap to use `quarto.runSelection` rather than `r.runSelection` when using Julia.

```
{
        "key": "ctrl+enter",  
        "command": "quarto.runSelection",
        "when": "editorTextFocus && editorLangId == quarto || editorLangId == julia"
    }
```

**Comment by mcanouil** [comment]
@jjallaire I believe your commit 0ac9f340a5cf1b9af10aecc097601fb27a98f034 released in v1.54.0 solved this issue, isn't it?

**Comment by jjallaire** [comment]
Yes, it should indeed!

**Comment by mcanouil** [comment]
It did in my case (I just had to add an exception in one my custom shortcut).

I also asked some feedback on Twitter from some folks that had the issue described here.
