### ISSUE TITLE
Preview not refreshing after file changes

### ISSUE THREAD

**Issue by rpodcast** [quarto-dev/quarto-vscode#6]
I'm using quarto within my remote containerized VS-Code dev environment, and I cannot get the  live preview of an HTML-based format (such as HTML report or revealjs presentation)  to refresh after saving file changes to the source `.qmd` file. I launched the preview by selecting `Quarto: Render Document` in the command palette. 

I also noticed that initially the preview tab in VS-code is blank until I hit the refresh button, and then the rendered slides appear. But the preview will not update when using the built-in preview tab or pop out to a web browser tab. 

My repository with the slides and report sources (as well as my dev environment setup) is available at [github.com/rpodcast/quartoplay](https://github.com/rpodcast/quartoplay).

Version information:

* VS-Code `1.66.0`
* quarto `0.9.172`
* R version `4.1.0`
* Quarto extension `v1.11.2`
* R extension `v2.4.0`

**Comment by jjallaire** [comment]
One thing to know is that just as with RStudio the preview doesn't refresh unless you actually render the document again (it doesn't trigger on save). We will soon provide an option for render on save but that's not how it works right now.

The preview being blank at the outset could be a side effect of running in a remote containerized dev environment? (I don't have this setup locally so can't know for sure). I noticed here (https://github.com/rpodcast/quartoplay/tree/main/.devcontainer#visual-studio-code-setup) that you mention a similar issue with running Shiny applications. This to me points to some sort of general disconnect on embedded browsers in this configuration. You could try executing the "Developer: Open Webview Developer Tools" command and then seeing if you get more a more comprehensive picture (errors, etc.) for both the Quarto and Shiny cases.

**Comment by rpodcast** [comment]
I will fire up virtual machines with native VS-Code & quarto installations and report back my findings. After some recent improvements in the R extenston, live preview for compiling Rmarkdown documents works out of the box in VS-Code without any additional refreshes. I forgot to update my development environment readme but Shiny apps now load correctly with the R extension as well.

**Comment by rpodcast** [comment]
Finally spun up a Linux virtual machine and while the preview page loads correctly after the initial render, the live preview still does not update when saving the document. Additional info:
* Distribution: Ubuntu Mate 21.10
* R: Version 4.1.3
* VS-Code: Version 1.66.1
* Quarto extension: Version 1.12.1

On the same Linux VM, I was able to get live preview working just fine with RStudio Desktop.

**Comment by jjallaire** [comment]
In VS code we don't currently have "Preview on Save" (you actually need to re-render). Note that re-rendering also saves so it's effectively one command either way (Ctrl+Shift+K to render)

**Comment by rpodcast** [comment]
I understand now. I was incorrectly assuming it was a same rendering process as utilized by the R extension that provides re-rendering automatically on saving an R markdown document (which integrates directly in the R session, as opposed to Quarto running from the cli). I just need to train myself with this workflow. Thank you for clearing this up!

**Comment by jjallaire** [comment]
We will soon add the option in the VS Code extension to do "Render on Save". Our feeling is that for document that take a long time to render (e.g. > 1 minute) that conflating render and save is actively bad (b/c you might want to save/commit your work w/o the long render). That's how we handle it in RStudio and we're hoping to do the same in VS Code.
