### ISSUE TITLE
VScode: Quarto Installation Not Found

### ISSUE THREAD

**Issue by VitorBSP** [quarto-dev/quarto-vscode#60]
I trying a lot of things to use Quarto in VSCode, but none worked, Quarto still not working in VScode, but works very well in RStudio.

The problem:
![image](https://user-images.githubusercontent.com/21180412/184892108-f28e5deb-b608-492e-afbe-7d6fcb7285cb.png)
But extension is installed:
![image](https://user-images.githubusercontent.com/21180412/184895169-48fd0d52-4b53-423c-9cab-0c6cc336e0b0.png)
And Quarto too:
![image](https://user-images.githubusercontent.com/21180412/184892894-254d5b01-d8aa-4e29-8358-13a472d9f212.png)

Some things I've tested/tried:
![image](https://user-images.githubusercontent.com/21180412/184893222-0b402c8c-3359-45ce-b94d-8f32359a64e6.png)
None of that worked in VSCode terminal, but in linusxbash:
![image](https://user-images.githubusercontent.com/21180412/184893787-8d02d1ec-1fdc-4b98-93dc-add283cae93f.png)
And works in RStudio terminal too:
![image](https://user-images.githubusercontent.com/21180412/184894115-45f0649d-20a4-4e68-bcc0-7cb8a73c0efd.png)
And rendering works with `quarto preview apresentacao.qmd`
![image](https://user-images.githubusercontent.com/21180412/184894694-5d5d8670-9207-4b4b-99fe-6c68ee6daff7.png)
<details>
<summary>my configs</summary>
<br>

R version: 4.2.1

os: Pop!_OS 22.04 LTS

system: x86_64, linux-gnu

rstudio: 2022.02.3+492 Prairie Trillium (desktop)

pandoc: 2.17.1.1 @ /usr/lib/rstudio/bin/quarto/bin/ (via rmarkdown)

vscode: 1.68.1
</details>

Am I doing something wrong?

**Comment by jjallaire** [comment]
Either Quarto isn't on the PATH within VS Code or there is some problem running Quarto from VS Code. From a terminal in VS Code what happens if you execute `which quarto` ?

The VS Code extension also has a setting for providing an explicit path to Quarto so you might give that a try as well.

**Comment by jjallaire** [comment]
You need to arrange for Quarto to be on your system PATH when running VS Code (you should consult the appropriate documentation on how to do this)
