### ISSUE TITLE
"No TeX installation was detected" even after "quarto install tool tinytex"

### ISSUE THREAD

**Issue by MagentaPhoton** [quarto-dev/quarto-vscode#68]
This issue for **quarto-vscode** (installed today, Saturday 2022.08.27) is identical to [issue #1116 for quarto-cli](https://github.com/quarto-dev/quarto-cli/issues/1116): Even after executing `quarto install tool tinytex`, attempting to `Render PDF` fails. The error message is as follows.

> running xelatex - 1
> 
> No TeX installation was detected.
> 
> Please run 'quarto install tool tinytex' to install TinyTex.
> If you prefer, you may install TexLive or another TeX distribution.

Per the instructions given in response to issue #1116 for quarto-cli, I un-installed and then re-installed tinytex, but the problem remains. Attempting to run `quarto install tool tinytex` again yields the message **tinytex is already installed and up to date.**

**Comment by dragonstyle** [comment]
Sorry that you've run into this!

- What platform is this occurring on?

- Would you mind going through the remove/add process again and sharing the output of the `quarto install tool tinytex` command? I'm thinking perhaps we're failing creating a symlink (if this is a 'nix based system).

**Comment by MagentaPhoton** [comment]
@dragonstyle Thank you for responding. I am **very** impressed by Quarto.

After un-installing and re-installing again and seeing some messages that I had not noticed before, I did some digging on my machine...and realized that **I didn't have TeX Live installed**!

I installed TeX Live, but now I have a different problem. When I try `Render PDF`, the tex file is generated flawlessly, but the tex-to-pdf step fails with the following error message.

```
running xelatex - 1
command xelatex not found, attempting install
finding package for xelatex
> 1 package to install
> installing xelatex (1 of 1)
ERROR: tlmgr returned a non zero status code

tlmgr: Remote repository is newer than local (2018 < 2022)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
```
 - My Linux distribution is MX Linux version [MX-19.4_x64](https://mxlinux.org/blog/mx-19-4-now-available/) (patito feo).
 - Installing TeX Live gave me XeTeX 3.14159265-2.6-0.99999 (TeX Live 2019/dev/Debian).
 
**How do I configure Quarto to be aware of the XeTeX that came when I installed TeX Live?**

Thanks in advance for advice and insight.

**Comment by ariewjy** [comment]
Hi, any quick solve for this? I have the same issue, and still not working as expected. 


<img width="637" alt="image" src="https://user-images.githubusercontent.com/73975333/197385392-5c47911a-69dc-44cc-879a-48686d1836ae.png">

**Comment by mcanouil** [comment]
Hi, could you provide the output of:

- `quarto check`
- `quarto list tools`

**Comment by jjallaire** [comment]
In version 1.2 we have made some changes to how tinytex is installed/discovered which might get this working. You can download the pre-release of v1.2 here: https://quarto.org/docs/download/prerelease.html

**Comment by ariewjy** [comment]
All, thanks for the help. Installing the pre-release version of Quarto solved it.
