### ISSUE TITLE
Feature request: rainbow matching div classes

### ISSUE THREAD

**Issue by samrickman** [quarto-dev/quarto-vscode#69]
I have been using Quarto in vs code to make a revealjs presentation that mixes R, Python and javascript (plotly, mermaid) with various html stuff that could not be used in a pdf presentation, e.g. gifs, background iframes. It is awesome.

I love the vscode extension - the syntax highlighting works really well for the main document and all languages. The only thing is that when adding several `<div>` tags with a class attribute using the `:::` notation, it can get a bit confusing. For example:

```
# Slide title

:::: {.columns}

::: {.column width="50%"}
::: {layout="[[-1], [1], [-1]]"}
::: {.nonincremental}
1. Here is a point.<br>

2. This is another point.<br>

3. I have used the layout tag to make this appear in the centre of the screen [^reference1]<br>
:::
:::
:::

::: {.column width="50%"}
::: {layout="[[-1], [1], [-1]]"}
![](./plots/some-plot.png)
:::
:::

::::
[^reference1]: https://stackoverflow.com/questions/72941210/vertical-align-of-images-in-quarto-presentations
```

This is how this appears:

![image](https://user-images.githubusercontent.com/46163241/187399931-2a59d19d-ac0b-48aa-a210-92bdb5660d0c.png)

If these were nested brackets then vs code could highlight which close bracket matches each open bracket. I wondered whether it would be straightforward to add similar functionality for each `:::`?

**Comment by jjallaire** [comment]
I agree that nested divs are quite painful to edit! I'm not sure if the syntax highlighter has the ability to do coloring at that level (if not then there is a separate tokenizer interface we might be able to take advantage of). One thing you can do is to use varying numbers of colons (e.g. `::::: {.columns} <content> :::::`).

**Comment by samrickman** [comment]
Oh awesome thanks I didn't realise that. Is any set of 3+ colons interpreted as a div? Is this documented somewhere?

**Comment by jjallaire** [comment]
It's not in our docs but its in the Pandoc docs: https://pandoc.org/MANUAL.html#divs-and-spans (I'll update ours to mention this though)

**Comment by samrickman** [comment]
I did not realise this - it can be a bit hard to keep track of where to look sometimes - thanks for the link.
