### ISSUE TITLE
Exchange variable from Python and R cell like Rstudio?

### ISSUE THREAD

**Issue by antonio-yu** [quarto-dev/quarto-vscode#71]
In Rstudio, we could use variable of R in python chunck by  `r.variable`
and use variable of Python in R chunck by  `py$variable`

Any way to achieve this too in quarto-vscode in the future?

**Comment by jjallaire** [comment]
This will work so long as you are using Knitr as your `.qmd` engine (i.e. this feature isn't an RStudio feature but rather one from Knitr). You might not see code completion for this in VS Code but the feature is there.
