### ISSUE TITLE
Markdown shortcuts in qmd

### ISSUE THREAD

**Issue by Lightup1** [quarto-dev/quarto-vscode#72]
Is it possible to support shortcuts as vscode plugin "markdown all in one"?
For example, Ctrl+B to get bold environment ****

**Comment by jjallaire** [comment]
That is an oversight! Just implemented here: https://github.com/quarto-dev/quarto-vscode/commit/2033954ba0d6ed852b16de6df26dc5449957f69a

(will be in available in our next release which should be soon)
