### ISSUE TITLE
Render working directory

### ISSUE THREAD

**Issue by bernardkaplan** [quarto-dev/quarto-vscode#73]
When I try to render a qmd file using the "Render" button, the terminal window doesn't start in the project folder but in my home directory. 

Hence the file to render is not found.

I guess there is something wrong with my settings. Any idea ?

**Comment by jjallaire** [comment]
We are setting the current working directory of the terminal when we create it to the directory of the input file -- there is probably something in your shell that is then automatically switching it to your home directory. LMK if that's the case (and in any case we might consider rendering using the full path to the input to work around this possibility)

**Comment by bernardkaplan** [comment]
I indeed had a command (`Set-location $env:USERPROFILE`) that automatically switched powershell to my home directory in `C:\Users\xxx\Documents\WindowsPowerShell\profile.ps1`. No idea why I did it in the first place.

Everything is working fine now with the quarto extension.

**Comment by jjallaire** [comment]
Okay, great to know and thanks for the details on how this came to pass. I think I'll still put in some defensive code to make sure this won't trip others up in the future.

**Comment by jjallaire** [comment]
Okay, implemented a countermeasure for this here (https://github.com/quarto-dev/quarto-vscode/commit/0d25076c7b7afbe8e454cf99a100f65f9607d26e) will rely on a complimentary commit it Quarto CLI v1.2
