### ISSUE TITLE
"Toggle code" shortcut silently conflicts with "Add Selection to Next Find Match"

### ISSUE THREAD

**Issue by jimjam-slam** [quarto-dev/quarto-vscode#74]
It looks like the Quarto extension may have recently introduced a "Toggle Code" command (`quarto.toggleCode`) that is bound to `Ctrl+D` (or `Cmd+D` on macOS). This conflicts with an existing command, "Add Selection to Next Find Match", and that command is silently lost.

I can't speak to how many people generally use Ctrl+D to do multiple selections (I personally use constantly!), and I know that it's possible for users to remap commands themselves, but I think silently overwriting an existing base VSCode command is not ideal (recognising, of course, that there are quite a few of them!).

**Comment by jjallaire** [comment]
Thanks for pointing this out! I think all of the new formatting keyboard shortcuts were over-reaching. I've removed the default keybindings here (https://github.com/quarto-dev/quarto-vscode/commit/d289b610dbd80c33b7cc8c7e2d7e0da33d3a712c). Users can still of course bind them to whatever keys they want to we just wont do it by default.

This is available now in version 1.37.0
