### ISSUE TITLE
Render button fails for ipynb file (render works via terminal)

### ISSUE THREAD

**Issue by marcel-goldschen-ohm** [quarto-dev/quarto-vscode#78]
If I select Render from the button/menu at the top of a .qmd file toolbar, then Quarto opens a Terminal and successfully renders the file and shows a preview in a new window as desired.

If I do the same for a .ipynb file, nothing happens. However, I can successfully render and preview the .ipynb file by manually opening a Terminal and executing `quarto preview myfile.ipynb`, so it appears just the toolbar Render menubutton for .ipynb files is not working correctly.

* MacOS 12.4
* VS Code 1.71.0
* quarto 1.1.189
* VS Code Quarto Extension 1.38.0

**Comment by marcel-goldschen-ohm** [comment]
Update, the render button appears to work for some .ipynb files but not others. This is unfortunate, because it probably means the bug is not going to be obvious. I'll let you know if I figure out what the difference is, but don't hold your breath.

**Comment by jjallaire** [comment]
I'm also not able to reproduce this locally :-(  Any other details you might have are much appreciated.
