### ISSUE TITLE
custom.scss file not found

### ISSUE THREAD

**Issue by marcel-goldschen-ohm** [quarto-dev/quarto-vscode#79]
When rendering a .ipynb or .qmd file in VS Code with header that includes
```
format:
    revealjs:
        theme: [default, custom.scss]
```
I get the error `ERROR: NotFound: No such file or directory (os error 2)`.
If I remove the `custom.scss` file from the header, then my slides render just fine, albeit without my custom rules.
`custom.scss` is in the same folder as the .ipynb or .qmd file I am rendering.
What do I need to do to get quarto to find my `custom.scss` file?

* MacOS 12.4
* VS Code 1.71.0
* quarto 1.1.189
* VS Code Quarto Extension 1.38.0

**Comment by jjallaire** [comment]
I'm not able to reproduce this locally. Could you create a small git repo that reproduces the problem? 

Once the failure occurs, try defining `QUARTO_PRINT_STACK=true` in the Terminal and then running `quarto render` on the file (that would allow us to know what line of code is not finding an expected file).
