### ISSUE TITLE
Having trouble rendering Observable cells with the vscode exstension

### ISSUE THREAD

**Issue by scottfranz** [quarto-dev/quarto-vscode#8]
I have copied the example code chunks from the [Observable tutorial on Quarto](https://quarto.org/docs/computations/ojs.html). I have a downloaded palmer-penguin.csv file. But when I try to render command (ctrl + Shift + K ) as explained in the extension details. I get an error that says ```command 'quarto.render' not found.``` 

I also tried `quarto render PenguinExample.qmd` from my terminal and I get this error.

```
quarto : 
The term `quarto` is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path   
is correct and try again.
At line:1 char:1
+ quarto render PenguinExample.qmd
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (quarto:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException```

**Comment by scottfranz** [comment]
What a silly mistake. Thank you so much! Quarto looks amazing. Really excited about this work! I regularly use R and Observable together and I think this will enhanced my workflow immensely!

**Comment by jjallaire** [comment]
Great to hear! cc @cscheid
