### ISSUE TITLE
Preview seems to miss styles

### ISSUE THREAD

**Issue by domoritz** [quarto-dev/quarto-vscode#80]
When I open the preview, it looks like this

<img width="1349" alt="Screenshot 2022-09-13 at 14 33 34" src="https://user-images.githubusercontent.com/589034/189982709-85eaad13-8e91-4067-9bc7-baea56061714.png">

v1.38.0 in vscode 1.71.1.

**Comment by jjallaire** [comment]
That's actually not the Quarto preview, it's the VS Code Python Interactive Window (https://code.visualstudio.com/docs/python/jupyter-support-py).

**Comment by jjallaire** [comment]
i.e. you may need to modify the settings for the interactive window and/or file an issue on their repo.

**Comment by domoritz** [comment]
You are right. I see the same issue in notebooks. I need to see why that is happening. 

<img width="1190" alt="Screenshot 2022-09-13 at 17 57 33" src="https://user-images.githubusercontent.com/589034/190016654-b81c23c3-a48e-4e37-b8b1-296b6dad7f8b.png">
