### ISSUE TITLE
Preview TeX Maths breaks with a cross reference

### ISSUE THREAD

**Issue by iandol** [quarto-dev/quarto-vscode#81]
When I hover an equation, if there is a cross reference of the form:

```markdown
$$\frac{d}{dx}\left( \int_{a}^{x} f(u)\,du\right)=f(x).$$ {#eq-marginalia}
```

Then the preview fails to render:

![Screenshot 2022-09-21 at 13 43 50](https://user-images.githubusercontent.com/153905/191531445-7555c77b-5e72-4f6b-b9ca-6a5e869dd82d.png)

Adding a newline betwee `$$` and `{#...` and the preview works as expected (but a newline will then break the cross reference when rendering):

![Screenshot 2022-09-21 at 15 30 33](https://user-images.githubusercontent.com/153905/191532308-74f389e3-8e29-4cc5-a4db-044a283a8c6c.png)

**Comment by jjallaire** [comment]
Thanks for reporting this! Fix is here: https://github.com/quarto-dev/quarto-vscode/commit/8cc0a42132579c28a498bbc6556a08508f176180

Available in the latest release (v1.43.0)

**Comment by iandol** [comment]
Hi @jjallaire thank you. However I still don't see this working. Here is V1.43.0 with a space between the equation and label:
![Screenshot 2022-09-30 at 09 50 56](https://user-images.githubusercontent.com/153905/193173094-1d3c5d48-1c23-4fb4-975d-c7bd08280f1a.png)

Notice the grey background highlighting block extends down to the closing `:::`. If I add a newline before for the label then the grey background disappears and the equation renders:
![Screenshot 2022-09-30 at 09 50 21](https://user-images.githubusercontent.com/153905/193173332-fceb6b7d-73e6-4ea6-b4cf-d762e0055771.png)

There is some greedy regex or something eating up the block, here is an example without a surrounding div:

![Screenshot 2022-09-30 at 09 56 09_SMALL](https://user-images.githubusercontent.com/153905/193173635-ba1189fa-b4c2-4eae-97ba-3a406089f81e.png)

Here is the text for that example:

```markdown
See both @eq-one and @eq-two for more details:

$$t' = \frac{t - \dfrac{v}{c^{2}}x}{\sqrt{1 - \dfrac{v^{2}}{c^{2}}}}$$ {#eq-one}

Sint meis quo et, vis ad fæcete dolorem!   

$$\nabla \times \mathbf {H} ={\frac {1}{c}}\left(4\pi \mathbf {J} _{\text{f}}+{\frac {\partial \mathbf {D} }{\partial t}}\right)$$ {#eq-two}

Tritani posidonium suscipiantur ex duo, meæ essent mentitum ad.
```

**Comment by jjallaire** [comment]
Yeah, we aren't fully in control of those regexes unfortunately. If you try this it will work:

```
$$
t' = \frac{t - \dfrac{v}{c^{2}}x}{\sqrt{1 - \dfrac{v^{2}}{c^{2}}}}
$$ {#eq-one}
```

**Comment by iandol** [comment]
Ok, understood, and cheers!
