### ISSUE TITLE
Syntax Highlighting for $$ maths blocks

### ISSUE THREAD

**Issue by iandol** [quarto-dev/quarto-vscode#83]
This is very minor, but in a maths block delineated using `$$` only the first $ is highlighted as if it is inline:

![Screenshot 2022-09-30 at 09 50 21](https://user-images.githubusercontent.com/153905/193174148-e7717375-02c6-4b55-b6e2-71de697e084d.png)

**Comment by jjallaire** [comment]
Yes, that's because the highlighting regex assumes that display math will break out into multiple lines e.g.

```
$$
x + 1 
$$
```

We are using the built in VS Code markdown math highlighting rules which have this constraint.

**Comment by jjallaire** [comment]
If you want to do inline math you'd do this: `$x + 1$`

Both that and the multiline variation above for display math should give you the correct highlighting behavior.

**Comment by iandol** [comment]
Ok fair enough, thank you!
