### ISSUE TITLE
Render button fails on Windows when using bash terminal in VS Code

### ISSUE THREAD

**Issue by debbieyuster** [quarto-dev/quarto-vscode#84]
I'm using Windows 10, and clicking the Render button in VS Code causes a Windows-like path to be sent to the terminal, full of backslashes (quarto preview c:\path\to\file.qmd). However, my default terminal in VS Code is gitbash, not CMD or Powershell, so the terminal is expecting a bash-like path with forward slashes (C:/path/to/file.qmd). As a result, the backslashes are not properly understood, and I get the following error message upon clicking the Render button:
ERROR: c:pathtofile.qmd not found

I didn't have this problem a couple weeks ago - perhaps it was introduced in [this commit](https://github.com/quarto-dev/quarto-vscode/commit/085e8854f4588253fc5754d88fbeca367377d67f)?

As a workaround, I can render via command line from the VS Code terminal.

**Comment by debbieyuster** [comment]
It's only the initial rendering that fails with the Render button. Once I render from the command line and the preview window pops up, the Render button works properly for re-rendering. So I guess this issue isn't such a big deal (but a fix would still be great!).

**Comment by jjallaire** [comment]
Thanks for reporting this! I have resolved this here (https://github.com/quarto-dev/quarto-vscode/commit/72f5e4cf44094a2bce7bb9d0ded160e8b308e9a6). Will be available in the next release of the extension (probably within a few days).
