### ISSUE TITLE
commands not found

### ISSUE THREAD

**Issue by pawelru** [quarto-dev/quarto-vscode#85]
When trying to render a document I have got an error that command is not found. Actually none of the quarto commands works.

![image](https://user-images.githubusercontent.com/12943682/193599661-dacd3804-b2be-48ce-8c67-7ddcc3ca327d.png)

and when doing cmd+shift+k
![image](https://user-images.githubusercontent.com/12943682/193672745-1bcc4028-7f40-46af-8a51-6ffd75267648.png)

I am using:
- macOS Monterey 12.6
- Quarto 1.1.251
- Quarto-vscode v1.43.0

Please let me know if you need something more from my side.

In Rstudio I have everything working so it's VSCode related

**Comment by jjallaire** [comment]
This would occur if we can't locate Quarto on your system. This might be because Quarto isn't on the PATH or it might be because RStudio is installed i a location we don't expect. If it's not on your PATH then we look in the following locations:

- Applications/quarto/bin/quarto
- ${HOME}/Applications/quarto/bin/quarto
- /Applications/RStudio.app/Contents/MacOS/quarto/bin/quarto

Do you know where Quarto is installed? If not, try executing `which quarto` from the terminal within RStudio.

**Comment by pawelru** [comment]
Please find it attached

```
❯ which quarto
/usr/local/bin/quarto

❯ quarto --version
1.1.251

❯ echo $PATH
/usr/local/opt/openssl@3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/quarto/bin:/Users/ruckip/opt/miniconda3/bin:/Users/ruckip/opt/miniconda3/condabin:/usr/local/opt/openssl@3/bin
```

**Comment by pawelru** [comment]
I have the same output from shell terminal, bash terminal, RStudio terminal as well as VSCode terminal.

I have restarted VSCode and now when I do cmd+shift+k then there is an "Activating Extensions..." loader on the bottom-left bar for few seconds and then nothing. For the rest of commands I still got the same:
![image](https://user-images.githubusercontent.com/12943682/193677553-3f896547-30b3-4e1b-a4db-49c0c60592a0.png)

![image](https://user-images.githubusercontent.com/12943682/193677753-8f6c49db-2433-4b2d-9f80-bed9854cbe5c.png)

**Comment by jjallaire** [comment]
I'm not sure what's going on then. It seems as Quarto isn't found (meaning either the executable isn't there or it isn't callable/invoke-able).

What is the file extension of the document you are working with?

**Comment by pawelru** [comment]
This is `.qmd` file that is being correctly identified as a "Quarto" by VSCode
![image](https://user-images.githubusercontent.com/12943682/193683279-14a40b02-1f08-454c-8200-f09b3869f6d2.png)

As I have everything working in RStudio, it seems that everything is ok with quarto-cli itself. For me the connection between vscode-extension to quarto is somehow broken and I don't know how to check / debug this stuff. 

I tried to check my keybord shortcuts:
![image](https://user-images.githubusercontent.com/12943682/193683518-915f16e7-20b8-491e-8cd8-a0b6d4d90c96.png)
![image](https://user-images.githubusercontent.com/12943682/193683575-b85c48d0-fa6b-4d3f-a4b8-e628dd19b8bf.png)

This all is a default config and I am not seeing anything suspicious in there. 

None of quarto specific commands work for me including even creating a new document which should be quarto-cli independent. When I do cmd+shift+p (View-Command Palette) and then type "quarto.newdocument":
![image](https://user-images.githubusercontent.com/12943682/193684439-7d57fe61-5aa3-4b46-9d71-9c91d6845e5b.png)

How to check what's defined under "quarto.newdocument". Where is global registry of commands so that I can check if it is not missing?

**Comment by jjallaire** [comment]
If you just type `quarto.newDocument` in the keybindings view you'll likely see it.

I have no idea what might be amiss here. The commands seem to have been "registered" as per the keybindings UI

**Comment by pawelru** [comment]
So the output is the same as in case of render one. The commend is registered but is not executable.

Looked on SO and I have basically the same issue as described here: https://stackoverflow.com/questions/49534068/command-not-found-in-vscode-extension

However, the top-voted answer is not a root-cause here. I haven't dig any further.

Just curious. I was doing installing everything quarto related today - including this extension. Am I the only one who reports it? Can you please try on your own with the released version and check if you have the same?

**Comment by jjallaire** [comment]
You are indeed the only one reporting this right now :-( 

I reset my system to have all the same versions as you report and things work fine.

I sincerely wish I could do more but it's something peculiar to your environment going on here (as all the paths/versions/etc. seem to line up correctly).

**Comment by Bonnevie** [comment]
Just to corroborate, I also have this issue, and it is very recent - I was using quarto + VS code's interactive window just yesterday, but now I'm experiencing `quarto.runCurrentCell` not found, and the same for all other quarto commands.
Seems I just fixed it while typing this comment though: I am on Ubuntu and previously used the `apt` package manager to install Quarto which got me version `0.9.598`, and now I just manually updated to `1.1.251` and it appears to work again! It was not sufficient to reinstall the extension alone. But since this is the version @pawelru is on, and he already tried a reinstall I guess it might not help him.

**Comment by j-winters** [comment]
I duplicated the same issue on my Mac. The issue seems to begin with the Quarto extensions of v1.36.0 and later. When I installed v1.35.0 extension, I was able to render again.

**Comment by jjallaire** [comment]
Thanks, that stands to be quite helpful! I just did a diff between v1.35.0 and v1.36.0 and didn't see anything that stood out as potentially causing this issue. It would be helpful to know:

(1) Exactly what behavior you are seeing (it is "command not found" or just render appearing not to work)

(2) What version of VS Code you are running

(3) What version of Quarto you see for `quarto --version`

**Comment by pawelru** [comment]
> I duplicated the same issue on my Mac. The issue seems to begin with the Quarto extensions of v1.36.0 and later. When I installed v1.35.0 extension, I was able to render again.

I do confirm the above. Reverting back to v1.35.0 makes everything work and from v1.36.0 it is not working anymore. I haven't changed `quarto` version itself so it's still 1.1.251

**Comment by jjallaire** [comment]
My best guess at this point is that JavaScript exception is occurring sometime during the middle of Quarto extension initialization which prevents those commands from being registered. Hopefully the Help => Toggle Developer Tools will give us a clue!

**Comment by jjallaire** [comment]
Just to keep an easily accessible record of it, here are the diffs from 1.35 to 1.36: https://github.com/quarto-dev/quarto-vscode/compare/5e14c88d8fbe428d89710ca0fedf23a4e1df4c82...9fc7c5ab041c281e236d5c56acb2854edcce8d0e

**Comment by pawelru** [comment]
VSCode version
```
Version: 1.66.2 (Universal)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z (6 mos ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 21.6.0
```

I updated to the newest quarto extension and in the developer tools, before any quarto commands I see the following:
```
Activating extension 'quarto.quarto' failed: Extension 'quarto.quarto' CANNOT use API proposal: notebookDocumentEvents.
Its package.json#enabledApiProposals-property declares: [] but NOT notebookDocumentEvents.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api quarto.quarto.
```

How should I understand the above?

(I don't have any other records in the console after running other quarto commands.)

This is missing in v1.35.

**Comment by jjallaire** [comment]
Okay, we've figured out the problem! You are running version 1.66.2 (which in theory we are compatible with). You can see in this code that we are subscribing to an event that only exists in 1.67:

https://github.com/quarto-dev/quarto-vscode/compare/5e14c88d8fbe428d89710ca0fedf23a4e1df4c82...9fc7c5ab041c281e236d5c56acb2854edcce8d0e#diff-9317a765a7e36179d3a6f2d841bbf7ceaa7449a5beafb1a4812dce59f08fb10dR111-R121

The problem is that that event actually appears to be _present_ in v1.66 but it throws an exception when accessed (which prevents us from further initializing). 

I realize that you could mitigate this by just updating VS Code, but If you don't mind I'd love to try to resolve this and publish a new version of the extension to try w/ 1.66. Give me an hour or two and I should be able to get that published so you can test.

**Comment by jjallaire** [comment]
Okay, this commit should fix the problem: https://github.com/quarto-dev/quarto-vscode/commit/646c464afa94cbc229258f91b8d565c29f689763

This is available now in an updated release (v1.46.0). 

Thanks again for your help in diagnosing the problem!

**Comment by pawelru** [comment]
🎉 all working in v1.46 Thank you!

**Comment by ChuliangXiao** [comment]
> Okay, this commit should fix the problem: [646c464](https://github.com/quarto-dev/quarto-vscode/commit/646c464afa94cbc229258f91b8d565c29f689763)
> 
> This is available now in an updated release (v1.46.0).
> 
> Thanks again for your help in diagnosing the problem!


I'm having very similar issues as @pawelru did:
1. Non `run cell` bottom
2. `render` bottom not responding
3. `cmmand + shift + k` returning `command 'quarto.renderShortcut' not found`
using:
```
macOS Monterey 12.2.1
Quarto 1.1.251
Quarto-vscode v1.50.0
VSCode: 1.72.2
```
![image](https://user-images.githubusercontent.com/6011789/197342684-4f05c891-494b-41f2-b314-b1d79fc4aff7.png)

**Comment by jjallaire** [comment]
Try executing Help => Toggle Developer Tools and see if there are any JavaScript errors which are occurring when the Quarto extension is loaded. You might need to also execute the Developer => Reload Window command to cause the extension to re-initialize.

**Comment by ChuliangXiao** [comment]
> Try executing Help => Toggle Developer Tools and see if there are any JavaScript errors which are occurring when the Quarto extension is loaded. You might need to also execute the Developer => Reload Window command to cause the extension to re-initialize.

It's my mistake. I created `quarto/` folder and put `example.qmd` into it. After renaming it to `quarto-ex/`, all those three issues are gone.
Thank you for your prompt response, JJ.
