### ISSUE TITLE
Macro expand math preview

### ISSUE THREAD

**Issue by lcnhb** [quarto-dev/quarto-vscode#88]
It would be great if the math preview was aware of user-defined macros, the ones supported by pandoc, which are automatically expanded in processing. Otherwise, the preview is a mess. I understand that this might be a bit more of an involved change..

**Comment by jjallaire** [comment]
Thanks for pointing this out! This should resolved here: https://github.com/quarto-dev/quarto-vscode/commit/788f86410e83344df67147439fa037754634ec4b

This is available now in version 1.45.0 of the extension.

**Comment by lcnhb** [comment]
Wow, that's great!

I now have another problem: I have defined macros in a separate file that I include with quarto include shortcodes. Those do not get detected. It would be very good to have a metadata field to set these sorts of macros that we want pandoc to expand regardless of output!

**Comment by jjallaire** [comment]
Okay, I think the best course would be as you suggest to add a `latex-macros` metadata field that tools could then read for extra definitions. I am going to transfer this issue to the quarto-cli repo so we can consider it there.
