### ISSUE TITLE
Command 'Quarto: New Notebook (ipynb)' when run as a first command after install

### ISSUE THREAD

**Issue by danieltomasz** [quarto-dev/quarto-vscode#9]
I really like the idea of quarto.When try to initialize quarto after installing with new ipbnv notebook  I got 
```
Command 'Quarto: New Notebook (ipynb)' resulted in an error (command 'quarto.newNotebook' not found)
```
However after creating qmd document I was able to  create ipynb notebooks  normally. 
Quarto 1.12.1 vscode  1.66.1

**Comment by jjallaire** [comment]
Thank you for reporting this! Should be fixed here: https://github.com/quarto-dev/quarto-vscode/commit/f268ab0f88d135312ebd4ae58c2039c185f5ceaf
