### ISSUE TITLE
Go to next and previous code chunk

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-vscode#92]
It would be great if go to next/previous code chunk features are provided in Quarto VSCode extension so that users can assign keyboard shortcuts (e.g., ctrl+pg-up/pg-down).

**Comment by werkstattcodes** [comment]
I added this to my keybinds.json. Works for me.

    {
      "key": "ctrl+u",
      "command": "quarto.goToNextCell"
    },
    {
      "key": "ctrl+i",
      "command": "quarto.goToPreviousCell"
    }

**Comment by jjallaire** [comment]
Yes, those commands are indeed there and can be assigned!
