### ISSUE TITLE
Adding more new file templates

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-vscode#94]
Currently, there are three new template commands are provided in Quarto extension: https://github.dev/quarto-dev/quarto-vscode/blob/main/src/providers/newdoc.ts#L21-L26

It would be even nicer if other templates (e.g., book, website, blog) could be added. For project-based templates, some default folder name could be provided like "draft" or something like that. In the long run,it would be fantastic if Quarto journal list could be fetched to easily create a journal template. VSCode-r extension, for example, supports a new Rmd draft command which is similar to what I have described here.

**Comment by jjallaire** [comment]
We've just added "Quarto: Create Project" to the latest version of the extension (v1.47.0) which handles websites, books, blogs, and simple default projects. We are in the course of creating a "Quarto: Create Extension" command that will do as you describe for journal templates.

**Comment by jooyoungseo** [comment]
Thanks for the prompt implementation! This is awesome! BTW, could it be made even better? Currently, users can only choose existing folder. If users type new folder name for Quarto project, it throws an error:

![image](https://user-images.githubusercontent.com/19754711/195743579-62982c84-ec3e-4c9d-a679-007df9cb1920.png)

It would be even nicer if users could create a new project folder if the directory does not exist.
