### ISSUE TITLE
Need consistent result in New File with qmd and quarto

### ISSUE THREAD

**Issue by jooyoungseo** [quarto-dev/quarto-vscode#99]
## Current Issues

1. Execute `New File... Ctrl+Alt+Windows+N`

2. Compare the template results by typing "qmd" and "quarto": You will see more results with "quarto"

## Expected Behaviors

I know why they give the different results. However, it would be even nicer if the two serch (with extension and file type) could give the same results.

Additionally, it would be so great if Quarto: Create New Project could be also included in this new file list.

**Comment by jjallaire** [comment]
Yeah, the qmd is there to distinguish between creating qmds and creating notebooks (ipynbs). I wouldn't want to include notebooks in the 'qmd` results as that wouldn't be quite right.

Will definitely add the Create Project command here in the next release!

**Comment by jjallaire** [comment]
Done here: https://github.com/quarto-dev/quarto-vscode/commit/f4bafbc897fef7203a84e4e77a467e3f377c8351

**Comment by jooyoungseo** [comment]
Awesome! It is getting so much better (so quickly)! ;)
